env:
  es2020: true
  node: true
  browser: true
extends:
  - airbnb
  - prettier
  - prettier/react
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
ignorePatterns:
  - gatsby-*.js
  - tailwind.config.js
  - '$virtual'
rules:
  jsx-a11y/label-has-associated-control:
    - error
    - assert: either
  react/prop-types:
    - off
